import Link from "next/link";
import { Check, Clock3, MapPin } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatMoney } from "@/lib/utils";
import { LanguageSwitcher } from "@/components/language-switcher";
import { getTranslator } from "@/lib/i18n-server";

function parseNonNegativeCents(value?: string) {
  const amount = Number(value);
  return Number.isFinite(amount) && amount >= 0 ? amount : 0;
}

export default async function PaymentSuccessPage({ searchParams }: { searchParams: Promise<{ order?: string; amount?: string; giftCard?: string; external?: string; demo?: string }> }) { const [params, t] = await Promise.all([searchParams, getTranslator()]); const amount = parseNonNegativeCents(params.amount); const giftCardAmount = parseNonNegativeCents(params.giftCard); const externalAmount = parseNonNegativeCents(params.external); return <main className="relative flex min-h-screen items-center justify-center px-5 py-10"><div className="absolute right-5 top-5"><LanguageSwitcher /></div><div className="w-full max-w-md rounded-[2rem] border bg-white p-7 text-center shadow-2xl shadow-black/5"><div className="mx-auto flex size-16 items-center justify-center rounded-full bg-black text-white"><Check className="size-7" /></div><p className="mt-6 text-xs uppercase tracking-[.22em] text-zinc-400">Payment completed</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.05em]">{t("支付完成")}</h1><p className="mt-3 font-mono text-2xl">{formatMoney(amount)}</p>{giftCardAmount > 0 && <div className="mt-5 space-y-2 rounded-2xl bg-zinc-100 p-4 text-left text-sm"><p className="flex items-center justify-between text-zinc-500"><span>{t("购物卡支付")}</span><span className="font-mono">{formatMoney(giftCardAmount)}</span></p><p className="flex items-center justify-between text-zinc-500"><span>{t("模拟付费")}</span><span className="font-mono">{formatMoney(externalAmount)}</span></p></div>}{params.demo === "1" && <p className="mx-auto mt-4 w-fit rounded-full bg-amber-50 px-3 py-1 text-xs text-amber-700">{t("演示模式 · 配置数据库后将真实持久化")}</p>}<div className="mt-7 space-y-3 rounded-2xl bg-zinc-100 p-5 text-left text-sm"><p className="flex items-center gap-3"><Clock3 className="size-4 text-zinc-400" />{t("预计 15–20 分钟后可取")}</p><p className="flex items-center gap-3"><MapPin className="size-4 text-zinc-400" />{t("CoffeeBar 安福路店")}</p><p className="font-mono text-xs text-zinc-400">{t("订单号")} {params.order ?? "—"}</p></div><div className="mt-6 grid grid-cols-2 gap-2"><Button asChild variant="outline"><Link href="/profile/orders">{t("查看订单")}</Link></Button><Button asChild><Link href="/menu">{t("继续点单")}</Link></Button></div></div></main>; }
