"use client";

import { useState, useTransition } from "react";
import { Bell, Boxes, ClipboardList, Coffee, LogOut, Plus, TrendingUp } from "lucide-react";
import { toast } from "sonner";
import { advanceOrder, createAnnouncement, toggleProduct, updateProduct } from "@/actions/admin";
import { Button } from "@/components/ui/button";
import { Input, Textarea } from "@/components/ui/input";
import { LanguageSwitcher } from "@/components/language-switcher";
import { useI18n } from "@/components/i18n-provider";
import { cn, formatMoney } from "@/lib/utils";

type ProductRow = { id: string; name: string; description: string; category: string; channel: string; basePrice: number; stock: number | null; imageUrl: string; isAvailable: boolean };
type OrderRow = { id: string; orderNumber: string; status: string; totalAmount: number; pickupName: string; pickupAt: string; items: { productName: string; quantity: number }[] };
type AnnouncementRow = { id: string; title: string; summary: string; status: string };
type AdminData = { products: ProductRow[]; orders: OrderRow[]; announcements: AnnouncementRow[]; revenue: number; paymentCount: number };

export function AdminConsole({ data, demo }: { data: AdminData; demo: boolean }) {
  const { t } = useI18n();
  const [tab, setTab] = useState<"overview" | "products" | "orders" | "messages">("overview");
  const [pending, startTransition] = useTransition();
  const nav = [{ id: "overview", label: "总览", icon: TrendingUp }, { id: "products", label: "商品", icon: Boxes }, { id: "orders", label: "订单", icon: ClipboardList }, { id: "messages", label: "消息", icon: Bell }] as const;
  function run(task: () => Promise<unknown>, success: string) { if (demo) return toast.info(t("演示模式：连接数据库并以管理员登录后可执行")); startTransition(async () => { try { await task(); toast.success(t(success)); } catch (error) { toast.error(t(error instanceof Error ? error.message : "操作失败")); } }); }
  return <div className="min-h-screen bg-zinc-100 md:grid md:grid-cols-[240px_1fr]"><aside className="border-b bg-black p-5 text-white md:sticky md:top-0 md:h-screen md:border-b-0"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-full bg-white text-black"><Coffee className="size-4" /></div><div><p className="font-semibold tracking-[-.04em]">COFFEEBAR</p><p className="text-[10px] uppercase tracking-[.15em] text-white/40">Operations</p></div></div><LanguageSwitcher inverted /></div><nav className="no-scrollbar mt-5 flex gap-2 overflow-x-auto md:mt-10 md:block md:space-y-1">{nav.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={cn("flex shrink-0 items-center gap-3 rounded-xl px-4 py-3 text-sm md:w-full", tab === id ? "bg-white text-black" : "text-white/55 hover:bg-white/10")}><Icon className="size-4" />{t(label)}</button>)}</nav><a href="/menu" className="mt-8 hidden items-center gap-3 rounded-xl px-4 py-3 text-sm text-white/55 md:flex"><LogOut className="size-4" />{t("返回用户端")}</a></aside><main className="p-5 md:p-10"><div className="mx-auto max-w-6xl">{demo && <div className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800">{t("当前为演示数据。配置数据库、运行种子并使用管理员账号登录后，管理操作会持久化。")}</div>}{tab === "overview" && <Overview data={data} />}{tab === "products" && <Products data={data.products} run={run} pending={pending} />}{tab === "orders" && <Orders rows={data.orders} run={run} />}{tab === "messages" && <Messages rows={data.announcements} run={run} />}</div></main></div>;
}

function Title({ eyebrow, children }: { eyebrow: string; children: React.ReactNode }) { return <div className="mb-7"><p className="text-xs uppercase tracking-[.2em] text-zinc-400">{eyebrow}</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.05em]">{children}</h1></div>; }
function Overview({ data }: { data: AdminData }) { const { t } = useI18n(); return <><Title eyebrow="Dashboard">{t("今日经营概览")}</Title><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[t("累计实收"), formatMoney(data.revenue)], [t("支付订单"), t("{count} 单", { count: data.paymentCount })], [t("在售商品"), `${data.products.filter((p) => p.isAvailable).length} ${t("件")}`], [t("待取订单"), t("{count} 单", { count: data.orders.filter((o) => o.status !== "COMPLETED").length })]].map(([label, value]) => <div key={label} className="rounded-[1.5rem] border bg-white p-5"><p className="text-xs text-zinc-500">{label}</p><p className="mt-3 font-mono text-2xl font-semibold">{value}</p></div>)}</div><div className="mt-5 rounded-[1.5rem] border bg-white p-6"><h2 className="font-semibold">{t("最近订单")}</h2><div className="mt-4 divide-y">{data.orders.slice(0, 5).map((order) => <div key={order.id} className="flex items-center justify-between py-4 text-sm"><div><p className="font-mono text-xs">{order.orderNumber}</p><p className="mt-1 text-zinc-400">{order.items.map((item) => `${t(item.productName)} ×${item.quantity}`).join(" · ")}</p></div><div className="text-right"><p>{formatMoney(order.totalAmount)}</p><p className="mt-1 text-xs text-zinc-400">{t(order.status)}</p></div></div>)}</div></div></>; }
function Products({ data, run, pending }: { data: ProductRow[]; run: (task: () => Promise<unknown>, success: string) => void; pending: boolean }) { const { t } = useI18n(); return <><Title eyebrow="Catalog">{t("商品管理")}</Title><div className="space-y-3">{data.map((product) => <details key={product.id} className="rounded-[1.25rem] border bg-white p-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-3"><div><p className="font-medium">{t(product.name)}</p><p className="mt-1 text-xs text-zinc-400">{product.channel} · {t(product.category)} · {formatMoney(product.basePrice)}</p></div><button onClick={(event) => { event.preventDefault(); run(() => toggleProduct(product.id, !product.isAvailable), product.isAvailable ? "商品已下架" : "商品已上架"); }} className={cn("rounded-full px-3 py-1 text-xs", product.isAvailable ? "bg-black text-white" : "bg-zinc-100 text-zinc-500")}>{t(product.isAvailable ? "在售" : "已下架")}</button></summary><form className="mt-5 grid gap-3 border-t pt-5 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); run(() => updateProduct({ id: product.id, name: form.get("name"), description: form.get("description"), basePrice: Math.round(Number(form.get("price")) * 100), stock: form.get("stock") === "" ? null : Number(form.get("stock")), imageUrl: form.get("imageUrl") }), "商品已更新"); }}><Input name="name" defaultValue={product.name} /><Input name="price" type="number" step="0.01" defaultValue={product.basePrice / 100} /><Input name="stock" type="number" defaultValue={product.stock ?? ""} placeholder={t("不限制库存")} /><Input name="imageUrl" defaultValue={product.imageUrl} /><Textarea name="description" defaultValue={product.description} className="sm:col-span-2" /><Button className="sm:w-fit" disabled={pending}>{t("保存修改")}</Button></form></details>)}</div></>; }
function Orders({ rows, run }: { rows: OrderRow[]; run: (task: () => Promise<unknown>, success: string) => void }) { const { t } = useI18n(); return <><Title eyebrow="Fulfillment">{t("订单管理")}</Title><div className="space-y-3">{rows.map((order) => <div key={order.id} className="rounded-[1.25rem] border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-xs text-zinc-400">{order.orderNumber}</p><p className="mt-2 font-medium">{order.pickupName} · {formatMoney(order.totalAmount)}</p><p className="mt-1 text-xs text-zinc-400">{order.items.map((item) => `${t(item.productName)} ×${item.quantity}`).join(" · ")}</p></div><span className="rounded-full bg-zinc-100 px-3 py-1 text-xs">{t(order.status)}</span></div><div className="mt-4 flex flex-wrap gap-2">{order.status === "PAID" && <Button size="sm" onClick={() => run(() => advanceOrder(order.id, "PREPARING"), "已开始制作")}>{t("开始制作")}</Button>}{order.status === "PREPARING" && <Button size="sm" onClick={() => run(() => advanceOrder(order.id, "READY"), "已通知取货")}>{t("标记可取")}</Button>}{order.status === "READY" && <Button size="sm" onClick={() => run(() => advanceOrder(order.id, "COMPLETED"), "订单已完成")}>{t("完成取货")}</Button>}</div></div>)}</div></>; }
function Messages({ rows, run }: { rows: AnnouncementRow[]; run: (task: () => Promise<unknown>, success: string) => void }) { const { t } = useI18n(); return <><Title eyebrow="Broadcast">{t("官方消息")}</Title><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); run(() => createAnnouncement({ title: form.get("title"), summary: form.get("summary"), content: form.get("content"), publish: form.get("publish") === "on" }), "消息已保存"); }} className="mb-6 space-y-3 rounded-[1.5rem] border bg-white p-6"><div className="flex items-center gap-2"><Plus className="size-4" /><h2 className="font-semibold">{t("创建消息")}</h2></div><Input name="title" placeholder={t("消息标题")} required /><Input name="summary" placeholder={t("一句话摘要")} required /><Textarea name="content" placeholder={t("消息正文")} required /><label className="flex items-center gap-2 text-sm"><input name="publish" type="checkbox" />{t("立即发布给全部用户")}</label><Button>{t("保存消息")}</Button></form><div className="space-y-3">{rows.map((item) => <div key={item.id} className="rounded-[1.25rem] border bg-white p-5"><div className="flex justify-between"><div><p className="font-medium">{t(item.title)}</p><p className="mt-1 text-sm text-zinc-500">{t(item.summary)}</p></div><span className="h-fit rounded-full bg-zinc-100 px-3 py-1 text-xs">{t(item.status)}</span></div></div>)}</div></>; }
