BEGIN;

ALTER TABLE "Order" DROP CONSTRAINT "Order_userId_fkey";

ALTER TABLE "Order" ADD CONSTRAINT "Order_userId_fkey"
FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

COMMIT;
